### ISSUE TITLE
no Windows binary release for Python 2.6

### ISSUE THREAD

**Issue by astraw** [visionegg/visionegg#3]
There is no VE binary available for download for Python 2.6 on Windows.

This is because PyOpenGL 3.0.0 has bug on Windows. Specifically,  multitexturing is broken, as reported ([SourceForge bug 2817196](http://sourceforge.net/tracker/index.php?func=detail&aid=2817196&group_id=5988&atid=105988)). This is evident when trying to use the Gabor stimuli, which will fail and an exception will be raised. The workaround is to continue using PyOpenGL 2.x, which unfortunately not available for Python 2.6.

**Comment by okbalefthanded** [comment]
@astraw 
Hi, is this bug being fixed ?

**Comment by astraw** [comment]
No, I was not working on this. Won't Python 2.7 work for you? (Why not?)

**Comment by okbalefthanded** [comment]
same issue on python 2.7 with PyOpenGL 3.1.0

**Comment by astraw** [comment]
Do you mean the [pyopengl multitexturing bug](https://sourceforge.net/p/pyopengl/bugs/216/)? Otherwise, what exactly is the issue?

**Comment by okbalefthanded** [comment]
Sorry my last comment wasn't precise, my issue is when I run any demo from the source code demo list I got this exception:

**File "C:\Anaconda2\lib\site-packages\OpenGL\arrays\numpymodule.py", line 28, in <module>
    from OpenGL_accelerate.numpy_formathandler import NumpyHandler
  File "**init**.pxd", line 155, in init OpenGL_accelerate.numpy_formathandler (src\numpy_formathandler.c:6155)
ValueError: ('numpy.dtype has the wrong size, try recompiling', 1, <OpenGL.platform.baseplatform.glGenTextures object at 0x0000000003DB32D0>)
Exception AttributeError: '**gl_module**' in <bound method TextureObject.__del__ of <VisionEgg.Textures.TextureObject object at 0x00000000082F9480>> ignored**

I'm running visionEgg on windows, My python packages are :
Interpereter: Anaconda 2.0.1 64 bit (because of numpy 1.8.1 that support Numeric).
PyOpenGL 3.1.1 64bit (from Gohlke python packages).

PS: I had perfectly run visionegg on ubuntu14.04 with the same packages versions

**Comment by okbalefthanded** [comment]
After installing the latest version with pip, I encountered an exception with the multitexturing warning:
"2016-08-15 21:09:22,934 (4368) WARNING: multitexturing not available.  Some features will not be available"
for example when running the alpha_texture demo the following exception is returned:

**Comment by okbalefthanded** [comment]
Here's the traceback of running Pyff with a visionEgg feedback : 

Traceback (most recent call last):
  File "D:\kach programmation wela walou\khadmation\byton\pyff\src\FeedbackBase\Feedback.py", line 462, in _playloop
    self._on_play()
  File "D:\kach programmation wela walou\khadmation\byton\pyff\src\FeedbackBase\Feedback.py", line 197, in _on_play
    self.on_play()
  File "D:\kach programmation wela walou\khadmation\byton\pyff\src\FeedbackBase\MainloopFeedback.py", line 67, in on_play
    self.pre_mainloop()
  File "Feedbacks\GazeIndependentSpeller\VisualSpellerVE.py", line 220, in pre_mainloop
    self.__idle()
  File "Feedbacks\GazeIndependentSpeller\VisualSpellerVE.py", line 413, in __idle
    self._presentation.go()
  File "C:\Anaconda\lib\site-packages\VisionEgg\FlowControl.py", line 395, in go
    viewport.draw()
  File "C:\Anaconda\lib\site-packages\VisionEgg\Core.py", line 1374, in draw
    stimulus.draw()
  File "C:\Anaconda\lib\site-packages\VisionEgg\Text.py", line 179, in draw
    VisionEgg.Textures.TextureStimulus.draw(self) # call base class
  File "C:\Anaconda\lib\site-packages\VisionEgg\Textures.py", line 1465, in draw
    self.texture_object.set_wrap_mode_s( p.texture_wrap_s )
  File "C:\Anaconda\lib\site-packages\VisionEgg\Textures.py", line 506, in set_wrap_mode_s
    gl.glTexParameteri( self.target, gl.GL_TEXTURE_WRAP_S, wrap_mode)
  File "errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError (src\errorchecker.c:1218)
GLError: GLError(
    err = 1280,
    description = 'invalid enumerant',
    baseOperation = glTexParameteri,
    cArguments = (
        GL_TEXTURE_2D,
        GL_TEXTURE_WRAP_S,
        GL_CLAMP_TO_EDGE,
    )
)

**Comment by okbalefthanded** [comment]
I've been trying to figure out how to fix it, what I'de noticed is that the opengl_info.py script shows that the GL_VERSION is newer than the one used by GD generic (in my case it's 3.1.0 - build 9.17.10.4101) and the renderer is not the default microsoft driver, however one running any demo script visionegg uses  the GDI Generic driver with OpenGL 1.1.0, do you have any idea how this can be fixed?
